### ISSUE TITLE
Further usage of ghostscript

### ISSUE THREAD

**Issue by laurentmmeyer** [ochachacha/ps-wasm#3]
First, I tested the extension and it works really well. Congrats on that 🎉 

Then, I'm not sure that I really understand what has been done: when you say 

> Cross-compiling ghostscript was the nontrivial part of this project.

Do you mean that you have the whole ghostscript library in the wasm? If yes, does it mean that we can theoretically call other commands like the one I use to compress images in PDF to make my scanned PDF smaller.
```
gs -sDEVICE=pdfwrite -dCompatibilityLevel=1.4 -dPDFSETTINGS=/ebook \
-dNOPAUSE -dQUIET -dBATCH -sOutputFile=output.pdf input.pdf
```

because this command looks quite similar to the one used in the [background thread](https://github.com/ochachacha/ps-wasm/blob/7236d02878da61d2697e078923dfa6c9ff038620/extension/ps-wasm-chrome/background.js#L82)
```
arguments: ['-sDEVICE=pdfwrite', '-DBATCH', '-DNOPAUSE',
  	 '-q',
  	 '-sOutputFile=output.pdf', '-c', '.setpdfwrite <</AlwaysEmbed [/Helvetica /Times-Roman]>> setdistillerparams', '-f', 'input.ps']
```

As an extension, it means that we can run every ghostscript command in a (chrome) browser on the client directly. That would be amazing! 🤩 
Do you have plan to expose the API of the WASM so that it can be consumed more easily? If not can you give me design seeds so that I can give it a try?

**Comment by ochachacha** [comment]
Thanks! Yes, the entire ghostscript library is in the wasm, so your command should work. To be more precise, the entire "gs" executable is in there, and I'm essentially calling it via the command line.

Note that you need the gs.js file as well, which loads the wasm file and sets up additional support (e.g. receives syscalls). Both the js and the wasm file are standard outputs of emscripten and you can read about how to work with them [there](https://emscripten.org/index.html).

I don't plan to further wrap this calling procedure (it's minimal amount of code in any case) but you are very welcome to experiment on your own. Essentially everything is happening in the _GSPS2PDF function. Let me know if you have any questions!
