### ISSUE TITLE
.PS file it's not recognized if GET parameters are added to the postscript URL

### ISSUE THREAD

**Issue by Tarloth** [ochachacha/ps-wasm#4]
Hello! Thank you very much for this extension! 

I have a problem, when I open a postscript file that lacks parameters (under GET) the file is opened perfectly in the extension. When, on the other hand, the file contains parameters (same previous URL but with added parameters), despite having the mime type correctly set, the extension does not recognize the file as postscript and ignores it.

Do you have any idea how to solve this? THANK YOU

**Comment by ochachacha** [comment]
Unfortunately, as of chrome extension manifest v3, webRequestBlocking [has been replaced](https://developer.chrome.com/docs/extensions/migrating/blocking-web-requests/) by declarativeNetRequest, and the latter does not provide a way to read response headers. Consequently, we can no longer activate the plugin based on the MIME type. The current activation criterion is simply a regex comparison against `.*\\.ps(\\.gz)?$`, which is of course unsatisfying, but nothing much can be done unless Google changes their mind.

**Comment by Tarloth** [comment]
THANKS for your answer, the file have a .ps extensión but with a lot of
parameters after the ps, for example

http://tarloth/HCANK_xml/c/procura_llamados.ps?fdec=,&fmen=-&ffecha=dd/MM/yyyy&metodo=LPN&ptipo=a4&pori=Portrait&pab=0&pini=1&palto=842&pancho=595&psup=28&pinf=28&pizq=70&pder=28

But as you say, it's impossible to do something if Google block the better
efforts!!! Thanks four your work!

By the way, the document has the following header

%!PS-Adobe-3.0
%%Pages: (atend)
%%DocumentPaperSizes: a4
%%Orientation: Portrait
%%EndComments

but the extension recognizes it as a Letter but gsview recognizes it
correctly as a4 size. Any suggestion to a correct paper size setting?

THANKS AGAIN


Néstor D. Groel
Lórien Sistemas

**Comment by ochachacha** [comment]
My understanding is that gs (the main program) ignores [DSC comments](https://en.wikipedia.org/wiki/Document_Structuring_Conventions); these are handled by gsview separately. [This answer](https://stackoverflow.com/a/8715763) mentions a boolean flag called `ProcessDSC`, which I don't think exists anymore (I grepped the source code). You may have some luck with `ProcessDSCComment` (see [here](https://ghostscript.readthedocs.io/en/latest/Language.html#user-parameters) for documentation), which involves parsing these comments by yourself (example can be found [here](https://comp.lang.postscript.narkive.com/dXs1y6xa/getting-ghostscript-to-convert-dsc-comments-to-pdf-metadata)).

**Comment by Tarloth** [comment]
Thanks, I'll check it out. Perfect, I will looking for if GS recognizes the
setpagedevice command and then I will use it, it's easiest use the A4 DSC
but I can set the page size as GS decide withouth problem. Thanks again for
the links, I made this system 20 years ago, it is still in use and
spreading, but the lack of support and update in GSview forces me to review
everything and to be honest I forgot some things that I knew about
postscript at that time because it is not a language that you use all the
time.

THANKS AGAIN

Néstor D. Groel
Lórien Sistemas

**Comment by Tarloth** [comment]
Hi!
Confirmed, to correctly set the correct page size  you only need the
traditional/used command
<< /PageSize [595 842] >> setpagedevice  (for a4)

That's enough, nothing more, thank you very much

Néstor D. Groel
Lórien Sistemas
