### ISSUE TITLE
I want to use it in Electron, but it keeps reporting errors

### ISSUE THREAD

**Issue by FZliweiliang** [ochachacha/ps-wasm#5]

**Comment by ochachacha** [comment]
Hi, this is designed to work as a chrome extension and not a standalone library. If you hope to use it in other ways, you'll probably need to adapt the code in viewer.js to invoke the wasm library yourself. The code there should hopefully be self-explanatory, but please let me know if you have any questions.

**Comment by FZliweiliang** [comment]
It can be imported in Electron, but it will prompt me that 

```
Current allocation mode is local
Gs.js? B129:1998 Error:/typecheck in -- closefile--
```

**Comment by ochachacha** [comment]
This would suggest that ghostscript is running, and this is ghostscript complaining about your input file. Have you tried other files?
